# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Tomasz Olędzki
tagline: "My personal blog about Azure and PowerShell"
description: "My personal blog</br>about Azure and PowerShell."
url: http://TomaszOledzki.eu
baseurl: /

author:
  name: "Tomasz Olędzki"
  url: http://TomaszOledzki.eu

github_username: TomaszOledzki
facebook_username: tomaszoledzki82
linkedin_username: tomasz-oledzki
emailme: mailto:tomasz-blog@oledzki.eu

paginate: 5
google_analytics: "UA-142149926-1"
#bing_seo:         '154DCA37E7E262422CB48DC78B149247'

github:
  repo: https://github.com/TomaszOledzki/TomaszOledzki.github.io

plugins:
  [jekyll-gist, jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]